# Generated by Django 3.2.12 on 2023-01-25 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendaEnLinea', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(blank=True, max_length=9, null=True)),
                ('status', models.BooleanField(default=True)),
                ('precioTotal', models.IntegerField(default=0)),
                ('cedula', models.CharField(default='', max_length=11)),
                ('celular', models.CharField(default='', max_length=10)),
                ('direccion', models.CharField(default='', max_length=50)),
                ('departamento', models.CharField(default='', max_length=50)),
                ('ciudad', models.CharField(default='', max_length=50)),
                ('comentarios', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'pedidos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoPedido', models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('En proceso', 'En proceso'), ('En envío', 'En envío'), ('Pedido entregado', 'Pedido entregado')], default='Aceptado', max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('precioUnidad', models.IntegerField(default=0)),
                ('subTotal', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEnLinea.productos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Linea pedido',
                'verbose_name_plural': 'Lineas pedidos',
                'db_table': 'Lineapedidos',
                'ordering': ['created_at'],
            },
        ),
    ]
