# Generated by Django 4.1.2 on 2023-02-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='talla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
