# Generated by Django 4.1.5 on 2023-01-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'ordering': ['created_at'], 'verbose_name': 'Linea pedido', 'verbose_name_plural': 'Lineas pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['created_at'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
    ]
