# Generated by Django 3.2.12 on 2023-02-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_lineapedido_color_lineapedido_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='talla',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
