# Generated by Django 4.1.5 on 2023-01-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_lineapedido_preciototal_lineapedido_preciounidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='PrecioTotal',
        ),
        migrations.AddField(
            model_name='pedido',
            name='PrecioTotal',
            field=models.IntegerField(default=0),
        ),
    ]
