# Generated by Django 4.1.5 on 2023-01-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_lineapedido_preciototal_pedido_preciototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='subTotal',
            field=models.IntegerField(default=0),
        ),
    ]
