# Generated by Django 4.1.5 on 2023-01-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_lineapedido_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='PrecioTotal',
            new_name='precioTotal',
        ),
    ]
