# Generated by Django 4.1.5 on 2023-01-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_rename_preciototal_pedido_preciototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
