# Generated by Django 4.1.5 on 2023-01-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='departamento',
            field=models.CharField(default='', max_length=50),
        ),
    ]
