# Generated by Django 3.2.12 on 2023-01-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_ciudad_pedido_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comentarios',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
