# Generated by Django 3.2.12 on 2023-01-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_pedido_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cedula',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='pedido',
            name='celular',
            field=models.CharField(default='', max_length=10),
        ),
    ]
