# Generated by Django 4.1.5 on 2023-01-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_auto_20230112_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='estadoPedido',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('En proceso', 'En proceso'), ('En envío', 'En envío'), ('Pedido entregado', 'Pedido entregado')], default='Aceptado', max_length=50),
        ),
    ]
