# Generated by Django 3.2.12 on 2023-01-06 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('stripe_custome_id', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(default='user', max_length=30)),
                ('nombre2', models.CharField(default='default', max_length=30)),
                ('primerApellido', models.CharField(default='', max_length=50)),
                ('segundoApellido', models.CharField(default='', max_length=50)),
                ('departamento', models.CharField(choices=[('AMAZONAS', 'AMAZONAS'), ('ANTIOQUIA', 'ANTIOQUIA'), ('ARAUCA', 'ARAUCA'), ('ATLÁNTICO', 'ATLÁNTICO'), ('BOLÍVAR', 'BOLÍVAR'), ('BOYACÁ', 'BOYACÁ'), ('CALDAS', 'CALDAS'), ('CAQUETÁ', 'CAQUETÁ'), ('CASANARE', 'CASANARE'), ('CAUCA', 'CAUCA'), ('CESAR', 'CESAR'), ('CHOCÓ', 'CHOCÓ'), ('CÓRDOBA', 'CÓRDOBA'), ('CUNDINAMARCA', 'CUNDINAMARCA'), ('DISTRITO CAPITAL', 'DISTRITO CAPITAL'), ('GUAINÍA', 'GUAINÍA'), ('GUAVIARE', 'GUAVIARE'), ('HUILA', 'HUILA'), ('LA GUAJIRA', 'LA GUAJIRA'), ('MAGDALENA', 'MAGDALENA'), ('META', 'META'), ('NARIÑO', 'NARIÑO'), ('NORTE DE SANTANDER', 'NORTE DE SANTANDER'), ('PUTUMAYO', 'PUTUMAYO'), ('QUINDÍO', 'QUINDÍO'), ('RISARALDA', 'RISARALDA'), ('SAN ANDRÉS Y PROVIDENCIA', 'SAN ANDRÉS Y PROVIDENCIA'), ('SUCRE', 'SUCRE'), ('TOLIMA', 'TOLIMA'), ('VALLE', 'VALLE'), ('VAUPÉS', 'VAUPÉS'), ('VICHADA', 'VICHADA')], default='', max_length=50)),
                ('ciudad', models.CharField(default='', max_length=50)),
                ('celular', models.CharField(default='', max_length=10)),
                ('direccion', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
