# Generated by Django 3.2.12 on 2023-03-01 03:57

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre')),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/Categorías')),
                ('banner', models.ImageField(blank=True, default='static/img/banner.jpg', null=True, upload_to='img/Categorías/banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=70)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='codigo')),
                ('marca', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.IntegerField(default=0)),
                ('descuento', models.IntegerField(blank=True, default=0, null=True)),
                ('PrecioSinDescuento', models.IntegerField(blank=True, default=0, null=True)),
                ('destacado', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('stock_total', models.IntegerField(default=0)),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Unisex', 'Unisex'), ('No definido', 'No definido')], default='No definido', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEnLinea.categoria')),
            ],
            options={
                'verbose_name_plural': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderImg', models.ImageField(default='static/img/Slider1.png', upload_to='img/Sliders')),
                ('nombreBanner', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tallas', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XS', 'XS'), ('XXS', 'XXS'), ('XXXS', 'XXXS'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('Talla Unica', 'Talla Unica')], default='Talla Unica', max_length=50)),
                ('colores', models.CharField(blank=True, choices=[('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Azul', 'Azul'), ('Rojo', 'Rojo'), ('Verde', 'Verde'), ('Marron', 'Marron'), ('Gris', 'Gris'), ('Rosa', 'Rosa'), ('Purpura', 'Purpura'), ('Naranja', 'Naranja'), ('Amarillo', 'Amarillo'), ('Olivo Oscuro', 'Olivo Oscuro'), ('Rosa Claro', 'Rosa Claro'), ('Azul Claro', 'Azul Claro'), ('Palo Rosa', 'Palo Rosa'), ('', 'No incluye colores'), ('Multicolor', 'Multicolor')], default='', max_length=50, null=True)),
                ('stock', models.IntegerField(default=1)),
                ('imagen', models.ImageField(blank=True, default='static/img/logo.png', null=True, upload_to='img/Productos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='tiendaEnLinea.productos')),
            ],
        ),
        migrations.CreateModel(
            name='comentariosProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('comentario_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('producto_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEnLinea.productos')),
            ],
        ),
    ]
