# Generated by Django 3.2.12 on 2023-01-06 00:34

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre')),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/Categorías')),
                ('banner', models.ImageField(blank=True, default='static/img/banner.jpg', null=True, upload_to='img/Categorías/banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderImg', models.ImageField(default='static/img/Slider1.png', upload_to='img/Sliders')),
                ('nombreBanner', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='codigo')),
                ('imagen', models.ImageField(blank=True, default='static/img/logo.png', null=True, upload_to='img/Productos')),
                ('marca', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.IntegerField(default=0)),
                ('descuento', models.IntegerField(blank=True, default=0, null=True)),
                ('PrecioSinDescuento', models.IntegerField(blank=True, default=0, null=True)),
                ('destacado', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField(default=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEnLinea.categoria')),
            ],
            options={
                'verbose_name_plural': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='imagenesProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/Productos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tiendaEnLinea.productos')),
            ],
        ),
        migrations.CreateModel(
            name='comentariosProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('comentario_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('producto_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEnLinea.productos')),
            ],
        ),
    ]
