# Generated by Django 3.2.12 on 2023-03-01 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='colores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEnLinea.color'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tallas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEnLinea.talla'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('producto', 'tallas', 'colores')},
        ),
    ]
