# Generated by Django 3.2.12 on 2023-01-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='banner',
        ),
    ]
