# Generated by Django 3.2.12 on 2023-01-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0002_alter_imagenesproductos_colores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesproductos',
            name='colores',
            field=models.CharField(blank=True, choices=[('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Azul', 'Azul'), ('Rojo', 'Rojo'), ('Verde', 'Verde'), ('Marron', 'Marron'), ('Gris', 'Gris'), ('Rosa', 'Rosa'), ('Purpura', 'Purpura'), ('Naranja', 'Naranja'), ('Amarillo', 'Amarillo'), ('Olivo Oscuro', 'Olivo Oscuro'), ('Rosa Claro', 'Rosa Claro'), ('Azul Claro', 'Azul Claro'), ('Palo Rosa', 'Palo Rosa'), ('', 'No incluye colores'), ('Multicolor', 'Multicolor')], default='', max_length=50, null=True),
        ),
    ]
