# Generated by Django 3.2.12 on 2023-01-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0002_remove_categoria_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='banner',
            field=models.ImageField(blank=True, default='static/img/banner.jpg', null=True, upload_to='img/Categorías/banner'),
        ),
    ]
