# Generated by Django 3.2.12 on 2023-03-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0003_auto_20230301_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='colores',
            field=models.CharField(blank=True, choices=[('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Azul', 'Azul'), ('Rojo', 'Rojo'), ('Verde', 'Verde'), ('Marron', 'Marron'), ('Gris', 'Gris'), ('Rosa', 'Rosa'), ('Purpura', 'Purpura'), ('Naranja', 'Naranja'), ('Amarillo', 'Amarillo'), ('Olivo Oscuro', 'Olivo Oscuro'), ('Rosa Claro', 'Rosa Claro'), ('Azul Claro', 'Azul Claro'), ('Palo Rosa', 'Palo Rosa'), ('', 'No incluye colores'), ('Multicolor', 'Multicolor')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tallas',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XS', 'XS'), ('XXS', 'XXS'), ('XXXS', 'XXXS'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('Talla Unica', 'Talla Unica')], default='Talla Unica', max_length=50),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Talla',
        ),
    ]
