# Generated by Django 3.2.12 on 2023-03-06 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0004_auto_20230301_0017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
    ]
