# Generated by Django 4.1.5 on 2023-01-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0004_productos_colores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='colores',
        ),
    ]
