# Generated by Django 4.1.5 on 2023-01-18 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0005_remove_productos_colores'),
    ]

    operations = [
        migrations.CreateModel(
            name='coloresProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colores', models.IntegerField(choices=[('0', 'Negro'), ('1', 'Blanco'), ('2', 'Azul'), ('3', 'Rojo'), ('4', 'Verde'), ('5', 'Café'), ('6', 'Gris'), ('7', 'Rosa'), ('8', 'Purpura'), ('9', 'Naranja'), ('10', 'Amarillo'), ('11', 'olivo oscuro'), ('12', 'Rosa Claro'), ('13', 'Azul Claro'), ('14', 'Palo Rosa'), ('15', 'No incluye colores')], default=15)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='tiendaEnLinea.productos')),
            ],
        ),
    ]
