# Generated by Django 4.1.2 on 2023-02-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0005_remove_productos_stock_tallaproductos_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock_total',
            field=models.IntegerField(default=0),
        ),
    ]
