# Generated by Django 4.1.5 on 2023-01-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0006_coloresproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloresproducto',
            name='colores',
            field=models.IntegerField(choices=[(0, 'Negro'), (1, 'Blanco'), (2, 'Azul'), (3, 'Rojo'), (4, 'Verde'), (5, 'Café'), (6, 'Gris'), (7, 'Rosa'), (8, 'Purpura'), (9, 'Naranja'), (10, 'Amarillo'), (11, 'olivo oscuro'), (12, 'Rosa Claro'), (13, 'Azul Claro'), (14, 'Palo Rosa'), (15, 'No incluye colores')], default=15),
        ),
    ]
