# Generated by Django 4.1.2 on 2023-02-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0006_productos_stock_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Unisex', 'Unisex'), ('No definido', 'No definido')], default='No definido', max_length=20, null=True),
        ),
    ]
