# Generated by Django 4.1.5 on 2023-01-18 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0007_alter_coloresproducto_colores'),
    ]

    operations = [
        migrations.CreateModel(
            name='tallaProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tallas', models.IntegerField(choices=[(0, 'S'), (1, 'M'), (2, 'L'), (3, 'XS'), (4, 'XXS'), (5, 'XXXS'), (6, 'XL'), (7, 'XXL'), (8, 'XXXL'), (9, 'T34'), (10, 'T35'), (11, 'T36'), (12, 'T37'), (13, 'T38'), (14, 'T39'), (15, 'T40'), (16, 'T41'), (17, 'T42'), (18, 'T43'), (19, 'T44'), (20, 'T45'), (21, 'Talla Unica')], default=21)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='tiendaEnLinea.productos')),
            ],
        ),
    ]
