# Generated by Django 4.1.5 on 2023-01-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0008_tallaproductos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloresproducto',
            name='colores',
            field=models.CharField(choices=[('0', 'Negro'), ('1', 'Blanco'), ('2', 'Azul'), ('3', 'Rojo'), ('4', 'Verde'), ('5', 'Café'), ('6', 'Gris'), ('7', 'Rosa'), ('8', 'Purpura'), ('9', 'Naranja'), ('10', 'Amarillo'), ('11', 'olivo oscuro'), ('12', 'Rosa Claro'), ('13', 'Azul Claro'), ('14', 'Palo Rosa'), ('15', 'No incluye colores')], default=15, max_length=50),
        ),
        migrations.AlterField(
            model_name='tallaproductos',
            name='tallas',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XS', 'XS'), ('XXS', 'XXS'), ('XXXS', 'XXXS'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('T34', '34'), ('T35', '35'), ('T36', '36'), ('T37', '37'), ('T38', '38'), ('T39', '39'), ('T40', '40'), ('T41', '41'), ('T42', '42'), ('T43', '43'), ('T44', '44'), ('T45', '45'), ('TU', 'Talla Unica')], default='TU', max_length=50),
        ),
    ]
