# Generated by Django 3.2.12 on 2023-01-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0009_alter_coloresproducto_colores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloresproducto',
            name='imagen',
            field=models.ImageField(default=True, upload_to='img/Productos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coloresproducto',
            name='colores',
            field=models.CharField(choices=[('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Azul', 'Azul'), ('Rojo', 'Rojo'), ('Verde', 'Verde'), ('Marron', 'Marron'), ('Gris', 'Gris'), ('Rosa', 'Rosa'), ('Purpura', 'Purpura'), ('Naranja', 'Naranja'), ('Amarillo', 'Amarillo'), ('Olivo Oscuro', 'Olivo Oscuro'), ('Rosa Claro', 'Rosa Claro'), ('Azul Claro', 'Azul Claro'), ('Palo Rosa', 'Palo Rosa'), ('15', 'No incluye colores')], default=15, max_length=50),
        ),
        migrations.AlterField(
            model_name='tallaproductos',
            name='tallas',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XS', 'XS'), ('XXS', 'XXS'), ('XXXS', 'XXXS'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('Talla Unica', 'Talla Unica')], default='Talla Unica', max_length=50),
        ),
        migrations.DeleteModel(
            name='imagenesProductos',
        ),
    ]
