# Generated by Django 3.2.12 on 2023-01-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0010_auto_20230118_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='coloresproducto',
            name='imagen',
            field=models.ImageField(blank=True, default='static/img/logo.png', null=True, upload_to='img/Productos'),
        ),
    ]
