# Generated by Django 3.2.12 on 2023-01-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEnLinea', '0011_auto_20230118_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coloresProducto',
            new_name='imagenesProductos',
        ),
    ]
